/* 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var first = 1;
var second = 2;
var sum = 2;

while(second < 4e6){
    var current = first + second;
    if (current%2 ==0){
        sum+=current;
    }
    first = second;
    second = current;
}

console.log(sum);